export const navData = [
    { title: "EODB", link: "/",
        submenu: [
            { title: "Online Dashboard", link: "/children" },
            { title: "SOP & Timeline", link: "/parents" },
            { title: "Comprehensive Checklist", link: "/seniors" },
            { title: "Labour Regulations Enablers", link: "/seniors" },
            { title: "Self Certification", link: "/seniors" },
        ]
     },
    { title: "License Fees", link: "/about",
        submenu: [
            { title: "License Fees 2006-2015", link: "/mission" },
            { title: "License Fees 2016", link: "/team" },
            { title: "License Fees 2017 Onwards", link: "/careers" },
        ]
     },
    { title: "Services", link: "/services",
        submenu: [
            { title: "Approval of Plan", link: "/consulting" },
            { title: "Registration and grant of license", link: "/implementation" },
            { title: "Renweal of License", link: "/training" },
        ]
     },
    { title: "Act, Rules & Forms", link: "/contact",
        submenu: [
            { title: "Act & Rules", link: "/contact" },
            { title: "Form 2", link: "/contact" },
            { title: "Form 22", link: "/contact" },
            { title: "Form 23", link: "/contact" },
            { title: "Form IV", link: "/contact" },
            { title: "Form Maternity Benefit (Rule 16)", link: "/contact" },
            { title: "Common Application Form", link: "/contact" },
            { title: "Form 18 (Notice Of Accident)", link: "/contact" },
            { title: "Form 23 A", link: "/contact" },
            { title: "Silicosis Policy Forms", link: "/contact" },


        ]
     },
     {title: "Notice/Circular", link:"/faq" },
     {title: "Zone", link:"/faq" },
     {title: "Factories", link:"/faq" },
     {title: "Inspections", link:"/faq" },
]


export const subMenuData = [
    {title: "Dashboard", link: "/" },
    {title: "Factories", link: "/parents",
        submenu: [
            { title: "All Factories search", link: "/custom-factory-search" },
            { title: "Crossed off Factories", link: "/CROSSED_OFF" },
        ]
     },
    {title: "Approval", link: "/seniors",
        submenu: [
            { title: "Pending Applications", link: "/pending-approvals" },
            { title: "Under Processed Applications", link: "/approval-status" },
            { title: "Back to Applicant Applications", link: "/approved-applications" },
            { title: "Rejected Applications", link: "/rejected-applications" },
            { title: "Issued Applications", link: "/all-applications" },
            {title: "All Zone All Plan Applications ", link: "/downloaded-applications" },  
        ]
     },
    {title: "Registration", link: "/seniors",
        submenu: [
            { title: "Pending Applications", link: "/reg-pending-applications" },
            { title: "Under Processed Applications", link: "/reg-under-process-applications" },
            { title: "Back for  Retification", link: "/reg-back-to-applicant-applications" },
        ]
     },
    {title: "Renewal", link: "/seniors" },
    {title: "Amendment", link: "/contact" },
    {title: "Reports", link: "/contact" },
        {title: "Form18", link: "/contact" },
        {title: "Inspection Report ", link: "/contact" },

]




export const user = {
    name: "AVIJIT BANERJEE",
    email: "ad25.doflb-wb@gov.in",
    role: "Inspector of Factories",
    avatar: "/api/placeholder/80/80" // Replace with actual avatar URL
  };



  export const factoriesData = [
    {
      id: 1,
      name: "M/S RADIANT RUBBER INDUSTRIES",
      section: "Section-85",
      address: "CHANDAN NAGAR,PO MOHESHTOLLA",
      zone: "CK",
      dateOfAmenability: "Not Available",
      regNo: "380-TP/Z/86",
      regDate: "Not Available",
      licenseNo: "380/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 2,
      name: "BALAJI AUTOCENTRE",
      section: "Section-85",
      address: "10, PASCHIM CHOUBHAGA, DHELENDIA, P.O. DHAPA",
      zone: "CG",
      dateOfAmenability: "Not Available",
      regNo: "880-TP/Z/2003",
      regDate: "Not Available",
      licenseNo: "880/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 3,
      name: "SUNRISE INDUSTRIES",
      section: "Section-85",
      address: "12, GARDEN REACH ROAD, KOLKATA",
      zone: "BK",
      dateOfAmenability: "Not Available",
      regNo: "456-TP/Z/90",
      regDate: "Not Available",
      licenseNo: "456/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 4,
      name: "STEEL FABRICATORS LTD",
      section: "Section-85",
      address: "PLOT NO 45, INDUSTRIAL AREA, HOWRAH",
      zone: "HW",
      dateOfAmenability: "Not Available",
      regNo: "234-TP/Z/88",
      regDate: "Not Available",
      licenseNo: "234/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 5,
      name: "BENGAL CHEMICALS",
      section: "Section-85",
      address: "56, MANIKTALA MAIN ROAD, KOLKATA",
      zone: "NK",
      dateOfAmenability: "Not Available",
      regNo: "678-TP/Z/92",
      regDate: "Not Available",
      licenseNo: "678/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 6,
      name: "PRECISION TOOLS MANUFACTURING",
      section: "Section-85",
      address: "LILUAH INDUSTRIAL ESTATE, HOWRAH",
      zone: "HW",
      dateOfAmenability: "Not Available",
      regNo: "789-TP/Z/95",
      regDate: "Not Available",
      licenseNo: "789/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 7,
      name: "METRO ENGINEERING WORKS",
      section: "Section-85",
      address: "23, JESSORE ROAD, KOLKATA",
      zone: "CK",
      dateOfAmenability: "Not Available",
      regNo: "901-TP/Z/98",
      regDate: "Not Available",
      licenseNo: "901/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 8,
      name: "PLASTIC PRODUCTS CO",
      section: "Section-85",
      address: "78, B.T. ROAD, NORTH 24 PARGANAS",
      zone: "BK",
      dateOfAmenability: "Not Available",
      regNo: "345-TP/Z/01",
      regDate: "Not Available",
      licenseNo: "345/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 9,
      name: "TEXTILE MILLS INDIA",
      section: "Section-85",
      address: "BALLY INDUSTRIAL AREA, HOWRAH",
      zone: "HW",
      dateOfAmenability: "Not Available",
      regNo: "567-TP/Z/04",
      regDate: "Not Available",
      licenseNo: "567/TP",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    },
    {
      id: 10,
      name: "INDIA INDUSTRIAL WORKS",
      section: "Section-2m(i)",
      address: "18/2, BRINDABAN MULLICK LANE, P.O. KADAMTALA",
      zone: "HB",
      dateOfAmenability: "Not Available",
      regNo: "88-HW/X/62",
      regDate: "Not Available",
      licenseNo: "5049",
      licenseDate: "Not Available",
      licenseExpireDate: "Not Available",
      commAddress: "Not Available",
      telephone: "Not Available",
      mobile: "Not Available",
      fax: "Not Available",
      email: "Not Available",
      status: "CROSSED OFF",
      statusDate: "14-05-2016"
    }
  ];